/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.example

import org.apache.commons.exec.CommandLine

class Library {
    boolean someLibraryMethod() {
        CommandLine cmdLine = new CommandLine("svnmucc");
		true
    }
}
